-- ============================================================================
-- AUREN — 02_seed_data.sql
-- DBMS Lab Mini Project | Component C: SQL Implementation (data population)
-- Populates core/transactional tables with realistic data (>=20 rows each,
-- per guideline). Lookup/reference tables were already seeded in
-- 01_schema.sql; this script assumes those fixed IDs (see comment map
-- at the top of that file / this generator script).
-- ============================================================================
USE auren_db;

-- ----------------------------------------------------------------------------
-- SECTION 1 — USERS (52 rows: 25 employers, 25 seekers, 2 admins)
-- ----------------------------------------------------------------------------
INSERT INTO Users (full_name, email, password_hash, role_id, phone, is_verified) VALUES
('Farhana Rahman', 'farhana.rahman1@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01746913810', TRUE),
('Sabbir Akter', 'sabbir.akter2@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01723756669', TRUE),
('Milton Islam', 'milton.islam3@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01714265799', TRUE),
('Karim Islam', 'karim.islam4@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01777827638', TRUE),
('Meherun Uddin', 'meherun.uddin5@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01797226012', TRUE),
('Rina Sheikh', 'rina.sheikh6@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01789089901', TRUE),
('Foysal Uddin', 'foysal.uddin7@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01731429110', FALSE),
('Ayesha Alam', 'ayesha.alam8@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01755176955', TRUE),
('Anwar Islam', 'anwar.islam9@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01758181396', TRUE),
('Nadia Alam', 'nadia.alam10@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01771662963', FALSE),
('Chondona Rahman', 'chondona.rahman11@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01760806024', FALSE),
('Habib Karim', 'habib.karim12@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01793016315', FALSE),
('Shakil Chowdhury', 'shakil.chowdhury13@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01716150444', FALSE),
('Lucky Akter', 'lucky.akter14@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01720709497', FALSE),
('Rupa Rahman', 'rupa.rahman15@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01770855700', TRUE),
('Farhana Begum', 'farhana.begum16@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01757683626', TRUE),
('Mahin Alam', 'mahin.alam17@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01796977837', FALSE),
('Farida Khan', 'farida.khan18@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01742857966', TRUE),
('Imran Mia', 'imran.mia19@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01795899313', TRUE),
('Rina Akter', 'rina.akter20@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01717507864', TRUE),
('Rupa Ahmed', 'rupa.ahmed21@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01763843426', FALSE),
('Foysal Islam', 'foysal.islam22@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01786125617', TRUE),
('Sohel Sarkar', 'sohel.sarkar23@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01777005685', TRUE),
('Rafiq Mia', 'rafiq.mia24@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01728740864', TRUE),
('Sabbir Alam', 'sabbir.alam25@auren-mail.com', '{bcrypt_placeholder_hash}', 1, '01767503414', FALSE),
('Hasan Molla', 'hasan.molla26@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01828566572', TRUE),
('Ruma Talukder', 'ruma.talukder27@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01816323852', TRUE),
('Shirin Hossain', 'shirin.hossain28@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01866661351', FALSE),
('Meherun Islam', 'meherun.islam29@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01889978790', TRUE),
('Arif Alam', 'arif.alam30@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01811540956', FALSE),
('Milton Rahman', 'milton.rahman31@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01882070937', FALSE),
('Moushumi Alam', 'moushumi.alam32@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01855657579', FALSE),
('Shirin Karim', 'shirin.karim33@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01870897765', TRUE),
('Rahim Alam', 'rahim.alam34@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01833978249', FALSE),
('Ruma Rahman', 'ruma.rahman35@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01850056581', FALSE),
('Farhana Chowdhury', 'farhana.chowdhury36@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01831682744', TRUE),
('Chondona Uddin', 'chondona.uddin37@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01875579548', TRUE),
('Karim Rahman', 'karim.rahman38@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01851273847', FALSE),
('Sabbir Ahmed', 'sabbir.ahmed39@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01886149359', TRUE),
('Habib Islam', 'habib.islam40@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01819289546', FALSE),
('Moushumi Hossain', 'moushumi.hossain41@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01873791320', TRUE),
('Rakib Khan', 'rakib.khan42@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01891415657', TRUE),
('Zahid Chowdhury', 'zahid.chowdhury43@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01836998038', FALSE),
('Sohel Karim', 'sohel.karim44@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01897225156', TRUE),
('Shakil Mia', 'shakil.mia45@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01870597444', FALSE),
('Shirin Akter', 'shirin.akter46@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01855377076', TRUE),
('Karim Akter', 'karim.akter47@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01810965138', TRUE),
('Farida Ahmed', 'farida.ahmed48@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01814216175', TRUE),
('Ayesha Islam', 'ayesha.islam49@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01847376585', TRUE),
('Lucky Talukder', 'lucky.talukder50@auren-mail.com', '{bcrypt_placeholder_hash}', 2, '01827758595', TRUE),
('Anika Talukder', 'anika.talukder51@auren-mail.com', '{bcrypt_placeholder_hash}', 3, '01942614537', TRUE),
('Sadia Talukder', 'sadia.talukder52@auren-mail.com', '{bcrypt_placeholder_hash}', 3, '01964634663', TRUE);

-- ----------------------------------------------------------------------------
-- SECTION 2 — EMPLOYERS (subtype rows for user_id 1..25)
-- First 20 employers are company-type, last 5 are individual-type.
-- ----------------------------------------------------------------------------
INSERT INTO Employers (user_id, employer_type_id) VALUES
(1, 2),
(2, 2),
(3, 2),
(4, 2),
(5, 2),
(6, 2),
(7, 2),
(8, 2),
(9, 2),
(10, 2),
(11, 2),
(12, 2),
(13, 2),
(14, 2),
(15, 2),
(16, 2),
(17, 2),
(18, 2),
(19, 2),
(20, 2),
(21, 1),
(22, 1),
(23, 1),
(24, 1),
(25, 1);

-- ----------------------------------------------------------------------------
-- SECTION 3 — SEEKERS (subtype rows for user_id 26..50)
-- ----------------------------------------------------------------------------
INSERT INTO Seekers (user_id) VALUES
(26),
(27),
(28),
(29),
(30),
(31),
(32),
(33),
(34),
(35),
(36),
(37),
(38),
(39),
(40),
(41),
(42),
(43),
(44),
(45),
(46),
(47),
(48),
(49),
(50);

-- ----------------------------------------------------------------------------
-- SECTION 4 — COMPANIES (20 rows, one per company-type employer)
-- ----------------------------------------------------------------------------
INSERT INTO Companies (employer_id, company_name, description, website, address, company_logo, industry_id, size_id) VALUES
(1, 'Deltamax Retail Ltd.', 'A growing retail business serving customers across Bangladesh.', 'https://www.deltamax.com.bd', 'House 25, Road 4, Dhaka', NULL, 1, 2),
(2, 'Green Valley Hospitality', 'A growing hospitality business serving customers across Bangladesh.', 'https://www.green.com.bd', 'House 91, Road 14, Dhaka', NULL, 2, 4),
(3, 'Skyline Construction Co.', 'A growing construction business serving customers across Bangladesh.', 'https://www.skyline.com.bd', 'House 120, Road 24, Dhaka', NULL, 3, 4),
(4, 'ByteWorks IT Solutions', 'A growing technology business serving customers across Bangladesh.', 'https://www.byteworks.com.bd', 'House 26, Road 2, Dhaka', NULL, 4, 1),
(5, 'BrightPath Education Group', 'A growing education business serving customers across Bangladesh.', 'https://www.brightpath.com.bd', 'House 87, Road 26, Dhaka', NULL, 5, 4),
(6, 'CarePlus Healthcare Services', 'A growing healthcare business serving customers across Bangladesh.', 'https://www.careplus.com.bd', 'House 64, Road 7, Dhaka', NULL, 6, 1),
(7, 'Swift Logistics BD', 'A growing logistics business serving customers across Bangladesh.', 'https://www.swift.com.bd', 'House 138, Road 15, Dhaka', NULL, 7, 2),
(8, 'Prime Manufacturing Ltd.', 'A growing manufacturing business serving customers across Bangladesh.', 'https://www.prime.com.bd', 'House 109, Road 6, Dhaka', NULL, 8, 2),
(9, 'Urban Nest Retail', 'A growing retail business serving customers across Bangladesh.', 'https://www.urban.com.bd', 'House 119, Road 8, Dhaka', NULL, 1, 3),
(10, 'Golden Spoon Hospitality', 'A growing hospitality business serving customers across Bangladesh.', 'https://www.golden.com.bd', 'House 114, Road 26, Dhaka', NULL, 2, 1),
(11, 'Foundation Builders Ltd.', 'A growing construction business serving customers across Bangladesh.', 'https://www.foundation.com.bd', 'House 26, Road 2, Dhaka', NULL, 3, 5),
(12, 'NextGen IT Consultancy', 'A growing technology business serving customers across Bangladesh.', 'https://www.nextgen.com.bd', 'House 4, Road 3, Dhaka', NULL, 4, 5),
(13, 'Scholar''s Home Education', 'A growing education business serving customers across Bangladesh.', 'https://www.scholars.com.bd', 'House 43, Road 14, Dhaka', NULL, 5, 2),
(14, 'Wellness First Clinic', 'A growing healthcare business serving customers across Bangladesh.', 'https://www.wellness.com.bd', 'House 124, Road 7, Dhaka', NULL, 6, 4),
(15, 'QuickMove Logistics', 'A growing logistics business serving customers across Bangladesh.', 'https://www.quickmove.com.bd', 'House 16, Road 6, Dhaka', NULL, 7, 4),
(16, 'Ironclad Manufacturing', 'A growing manufacturing business serving customers across Bangladesh.', 'https://www.ironclad.com.bd', 'House 1, Road 13, Dhaka', NULL, 8, 4),
(17, 'Metro Mart Retail', 'A growing retail business serving customers across Bangladesh.', 'https://www.metro.com.bd', 'House 117, Road 10, Dhaka', NULL, 1, 3),
(18, 'Riverside Resorts', 'A growing hospitality business serving customers across Bangladesh.', 'https://www.riverside.com.bd', 'House 143, Road 22, Dhaka', NULL, 2, 4),
(19, 'Apex Structures Ltd.', 'A growing construction business serving customers across Bangladesh.', 'https://www.apex.com.bd', 'House 40, Road 7, Dhaka', NULL, 3, 4),
(20, 'Cloudline Technologies', 'A growing technology business serving customers across Bangladesh.', 'https://www.cloudline.com.bd', 'House 56, Road 2, Dhaka', NULL, 4, 3);

-- ----------------------------------------------------------------------------
-- SECTION 5 — JOBS (30 rows)
-- ----------------------------------------------------------------------------
INSERT INTO Jobs (employer_id, company_id, category_id, area_id, salary_type_id, job_type_id, status_id,
                   title, description, requirements, pay_rate, vacancies, experience_required,
                   application_deadline, start_date, end_date, job_views, is_featured) VALUES
(19, 19, 1, 9, 1, 6, 1, 'Plumber Needed for 2-Day Apartment Fix', 'Fix leaking pipes and replace worn fittings in a 3-bedroom apartment.', '2+ years plumbing experience; own tools preferred.', 500.00, 4, '1+ years preferred', DATE_ADD(CURDATE(), INTERVAL 8 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 18 DAY), 41, FALSE),
(6, 6, 1, 2, 5, 1, 2, 'Electrician for Full Apartment Rewiring', 'Rewire an older apartment to meet current safety standards.', 'Certified electrician, 3+ years experience.', 1500.00, 4, 'No experience required', DATE_ADD(CURDATE(), INTERVAL 41 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 51 DAY), 20, FALSE),
(20, 20, 1, 2, 4, 6, 2, 'AC Technician for Servicing (4 Units)', 'Service and clean 4 split AC units before summer.', 'Experience with split AC systems.', 12000.00, 3, '2+ years required', DATE_ADD(CURDATE(), INTERVAL 18 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 28 DAY), 160, FALSE),
(8, 8, 2, 5, 4, 2, 2, 'Math Tutor for O-Level Student', 'Weekly tutoring sessions in algebra and geometry for a Grade 9 student.', 'Strong math background; tutoring experience preferred.', 2000.00, 4, '2+ years required', DATE_ADD(CURDATE(), INTERVAL 9 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 19 DAY), 288, TRUE),
(4, 4, 2, 2, 5, 2, 1, 'English Speaking Coach', 'Help a young professional improve spoken English fluency.', 'Fluent English; patient teaching style.', 1200.00, 3, 'No experience required', DATE_ADD(CURDATE(), INTERVAL 20 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 30 DAY), 80, FALSE),
(15, 15, 2, 9, 3, 5, 4, 'Physics Home Tutor (HSC)', 'Twice-weekly physics tutoring for HSC exam preparation.', 'Physics degree or equivalent teaching experience.', 12000.00, 1, '2+ years required', DATE_ADD(CURDATE(), INTERVAL 11 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 21 DAY), 68, FALSE),
(9, 9, 3, 2, 1, 6, 2, 'Waitstaff for Wedding Event', 'Serve food and drinks at a wedding reception for 200 guests.', 'Previous event service experience preferred.', 2000.00, 3, '1+ years preferred', DATE_ADD(CURDATE(), INTERVAL 26 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 36 DAY), 135, FALSE),
(17, 17, 3, 8, 3, 7, 1, 'Event Photographer for Corporate Function', 'Cover a half-day corporate event with photos and short video clips.', 'Own camera equipment; portfolio required.', 5000.00, 3, 'No experience required', DATE_ADD(CURDATE(), INTERVAL 5 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 15 DAY), 66, FALSE),
(21, NULL, 3, 5, 2, 6, 1, 'Stage Setup Crew for Concert', 'Help set up and break down stage equipment for an evening concert.', 'Physically able to lift equipment.', 5000.00, 1, 'No experience required', DATE_ADD(CURDATE(), INTERVAL 9 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 19 DAY), 76, FALSE),
(18, 18, 4, 1, 3, 5, 2, 'Bike Courier for Same-Day Delivery', 'Deliver parcels across Dhanmondi and Mohammadpur throughout the day.', 'Own motorbike and valid license.', 5000.00, 2, 'No experience required', DATE_ADD(CURDATE(), INTERVAL 24 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 34 DAY), 20, FALSE),
(12, 12, 4, 4, 2, 6, 1, 'Grocery Shopping Helper', 'Weekly grocery shopping and delivery for an elderly client.', 'Reliable and punctual.', 12000.00, 4, '1+ years preferred', DATE_ADD(CURDATE(), INTERVAL 20 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 30 DAY), 90, FALSE),
(14, 14, 4, 1, 2, 6, 4, 'Parcel Delivery — Gulshan Area', 'Deliver e-commerce parcels within Gulshan area for one week.', 'Own bicycle or motorbike.', 5000.00, 2, '2+ years required', DATE_ADD(CURDATE(), INTERVAL 15 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 25 DAY), 55, FALSE),
(13, 13, 5, 1, 4, 2, 1, 'WordPress Website Fix', 'Fix broken layout and update plugins on a small business website.', 'WordPress and basic PHP experience.', 8000.00, 3, '2+ years required', DATE_ADD(CURDATE(), INTERVAL 19 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 29 DAY), 98, FALSE),
(13, 13, 5, 6, 3, 7, 1, 'Home WiFi Setup & Troubleshooting', 'Set up a mesh WiFi network across a 3-floor house.', 'Networking basics; router configuration experience.', 2000.00, 3, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 39 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 49 DAY), 14, FALSE),
(4, 4, 5, 5, 2, 5, 4, 'Laptop Repair Technician', 'Diagnose and fix a laptop that won''t boot.', 'Hardware diagnostics experience.', 2000.00, 1, 'No experience required', DATE_ADD(CURDATE(), INTERVAL 43 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 53 DAY), 160, FALSE),
(14, 14, 6, 10, 5, 1, 1, 'Deep Cleaning for 3-Bed Apartment', 'One-time deep cleaning including kitchen and bathrooms.', 'Cleaning equipment provided by client.', 15000.00, 2, '2+ years required', DATE_ADD(CURDATE(), INTERVAL 7 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 17 DAY), 0, FALSE),
(17, 17, 6, 9, 2, 3, 1, 'Office Cleaning — Weekly Contract', 'Weekly evening cleaning for a small office space.', 'Reliable, background check preferred.', 3000.00, 3, 'No experience required', DATE_ADD(CURDATE(), INTERVAL 24 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 34 DAY), 209, FALSE),
(11, 11, 6, 7, 3, 5, 1, 'Move-out Cleaning Service', 'Full cleaning of an apartment before tenant handover.', 'Available on short notice.', 5000.00, 4, '1+ years preferred', DATE_ADD(CURDATE(), INTERVAL 44 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 54 DAY), 207, FALSE),
(18, 18, 7, 1, 3, 3, 1, 'Moving Help — Furniture Loading', 'Help load and unload furniture for an apartment move.', 'Physically fit; available on weekend.', 15000.00, 3, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 33 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 43 DAY), 109, FALSE),
(17, 17, 7, 8, 2, 6, 1, 'Warehouse Labor — 1 Week', 'General labor support in a warehouse for a short-term rush period.', 'Able to lift up to 25kg.', 12000.00, 3, 'No experience required', DATE_ADD(CURDATE(), INTERVAL 20 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 30 DAY), 115, FALSE),
(7, 7, 7, 3, 1, 1, 1, 'House Shifting Assistance', 'Assist a moving crew with packing and carrying boxes.', 'No experience required.', 8000.00, 1, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 31 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 41 DAY), 294, FALSE),
(7, 7, 8, 7, 4, 4, 1, 'Product Photography for E-commerce', 'Photograph 50 products for an online store catalog.', 'Own lighting and camera equipment.', 500.00, 1, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 19 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 29 DAY), 265, FALSE),
(15, 15, 8, 1, 5, 2, 4, 'Videographer for Birthday Event', 'Film a half-day birthday celebration and edit a highlight reel.', 'Video editing skills required.', 800.00, 4, '1+ years preferred', DATE_ADD(CURDATE(), INTERVAL 34 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 44 DAY), 286, FALSE),
(20, 20, 8, 6, 4, 5, 3, 'Portrait Photoshoot Session', 'One afternoon portrait session for a family of 4.', 'Portfolio of past portrait work.', 12000.00, 4, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 15 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 25 DAY), 243, FALSE),
(15, 15, 9, 5, 2, 7, 2, 'Excel Data Entry — 500 Records', 'Enter customer records into a structured Excel template.', 'Strong Excel skills; attention to detail.', 12000.00, 4, '1+ years preferred', DATE_ADD(CURDATE(), INTERVAL 22 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 32 DAY), 146, FALSE),
(8, 8, 9, 5, 3, 3, 3, 'Survey Data Digitization', 'Digitize 300 paper survey forms into a spreadsheet.', 'Fast and accurate typing.', 800.00, 2, '1+ years preferred', DATE_ADD(CURDATE(), INTERVAL 19 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 29 DAY), 78, FALSE),
(23, NULL, 9, 4, 1, 4, 1, 'Inventory Data Entry', 'Update inventory counts into the company''s tracking sheet.', 'Basic spreadsheet experience.', 12000.00, 4, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 8 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 18 DAY), 215, FALSE),
(13, 13, 10, 10, 1, 7, 3, 'Logo Design for Startup', 'Design a modern logo and basic brand guideline for a new startup.', 'Portfolio required; Adobe Illustrator skills.', 15000.00, 4, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 5 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 15 DAY), 152, FALSE),
(25, NULL, 10, 7, 4, 5, 3, 'Social Media Post Design (10 posts)', 'Design a set of 10 branded social media posts.', 'Canva or Adobe experience.', 12000.00, 2, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 19 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 29 DAY), 248, FALSE),
(1, 1, 10, 7, 3, 6, 2, 'Brochure Design — Print Ready', 'Design a tri-fold brochure ready for print.', 'Print design experience preferred.', 5000.00, 2, 'Entry-level welcome', DATE_ADD(CURDATE(), INTERVAL 13 DAY), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 23 DAY), 273, FALSE);

-- ----------------------------------------------------------------------------
-- SECTION 6 — RESUMES (25 rows — one per seeker, per the one-resume-per-seeker rule)
-- ----------------------------------------------------------------------------
INSERT INTO Resumes (seeker_id, headline, summary, education, experience, resume_path) VALUES
(26, 'Reliable handyman with 3 years of experience', 'Reliable handyman with 3 years of experience. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.A. in English, Jagannath University (2021)', '2 years of general labor and moving assistance work.', '/uploads/resumes/resume_26.pdf'),
(27, 'Warehouse and moving labor, physically fit', 'Warehouse and moving labor, physically fit. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Civil Engineering, BUET (2023)', '2 years freelancing on short-term local gigs.', '/uploads/resumes/resume_27.pdf'),
(28, 'Detail-oriented data entry specialist', 'Detail-oriented data entry specialist. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Civil Engineering, BUET (2023)', '6 months interning at a local design studio.', '/uploads/resumes/resume_28.pdf'),
(29, 'Freelance graphic designer and illustrator', 'Freelance graphic designer and illustrator. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.A. in English, Jagannath University (2021)', '1 year as a part-time tutor for high school students.', '/uploads/resumes/resume_29.pdf'),
(30, 'Reliable handyman with 3 years of experience', 'Reliable handyman with 3 years of experience. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'Diploma in Electrical Engineering, Dhaka Polytechnic (2020)', '6 months interning at a local design studio.', '/uploads/resumes/resume_30.pdf'),
(31, 'Enthusiastic event staff and photographer', 'Enthusiastic event staff and photographer. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'HSC, Dhaka College (2019)', '6 months interning at a local design studio.', '/uploads/resumes/resume_31.pdf'),
(32, 'Enthusiastic event staff and photographer', 'Enthusiastic event staff and photographer. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'Diploma in Electrical Engineering, Dhaka Polytechnic (2020)', '6 months interning at a local design studio.', '/uploads/resumes/resume_32.pdf'),
(33, 'Certified electrician available for short-term work', 'Certified electrician available for short-term work. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.A. in English, Jagannath University (2021)', '3 years working in retail customer service.', '/uploads/resumes/resume_33.pdf'),
(34, 'Detail-oriented data entry specialist', 'Detail-oriented data entry specialist. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.A. in English, Jagannath University (2021)', '2 years freelancing on short-term local gigs.', '/uploads/resumes/resume_34.pdf'),
(35, 'Junior web developer, WordPress specialist', 'Junior web developer, WordPress specialist. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Computer Science, University of Dhaka (2022)', '3 years working in retail customer service.', '/uploads/resumes/resume_35.pdf'),
(36, 'Experienced private tutor (Math & Physics)', 'Experienced private tutor (Math & Physics). Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Civil Engineering, BUET (2023)', '2 years freelancing on short-term local gigs.', '/uploads/resumes/resume_36.pdf'),
(37, 'Reliable handyman with 3 years of experience', 'Reliable handyman with 3 years of experience. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Computer Science, University of Dhaka (2022)', '1 year as a part-time tutor for high school students.', '/uploads/resumes/resume_37.pdf'),
(38, 'Experienced private tutor (Math & Physics)', 'Experienced private tutor (Math & Physics). Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Computer Science, University of Dhaka (2022)', '2 years of general labor and moving assistance work.', '/uploads/resumes/resume_38.pdf'),
(39, 'Freelance graphic designer and illustrator', 'Freelance graphic designer and illustrator. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'HSC, Dhaka College (2019)', '1 year as a part-time tutor for high school students.', '/uploads/resumes/resume_39.pdf'),
(40, 'Professional house cleaner, flexible schedule', 'Professional house cleaner, flexible schedule. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Civil Engineering, BUET (2023)', '2 years freelancing on short-term local gigs.', '/uploads/resumes/resume_40.pdf'),
(41, 'Warehouse and moving labor, physically fit', 'Warehouse and moving labor, physically fit. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'HSC, Dhaka College (2019)', '6 months interning at a local design studio.', '/uploads/resumes/resume_41.pdf'),
(42, 'Certified electrician available for short-term work', 'Certified electrician available for short-term work. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'Diploma in Electrical Engineering, Dhaka Polytechnic (2020)', '1 year as a part-time tutor for high school students.', '/uploads/resumes/resume_42.pdf'),
(43, 'Warehouse and moving labor, physically fit', 'Warehouse and moving labor, physically fit. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'SSC, Motijheel Model School (2017)', '1 year as a freelance photographer for local events.', '/uploads/resumes/resume_43.pdf'),
(44, 'Detail-oriented data entry specialist', 'Detail-oriented data entry specialist. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'HSC, Dhaka College (2019)', '3 years working in retail customer service.', '/uploads/resumes/resume_44.pdf'),
(45, 'Detail-oriented data entry specialist', 'Detail-oriented data entry specialist. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'SSC, Motijheel Model School (2017)', '2 years freelancing on short-term local gigs.', '/uploads/resumes/resume_45.pdf'),
(46, 'Certified electrician available for short-term work', 'Certified electrician available for short-term work. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'SSC, Motijheel Model School (2017)', '1 year as a freelance photographer for local events.', '/uploads/resumes/resume_46.pdf'),
(47, 'Dependable courier with own motorbike', 'Dependable courier with own motorbike. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.A. in English, Jagannath University (2021)', '1 year as a freelance photographer for local events.', '/uploads/resumes/resume_47.pdf'),
(48, 'Experienced private tutor (Math & Physics)', 'Experienced private tutor (Math & Physics). Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Computer Science, University of Dhaka (2022)', '2 years of general labor and moving assistance work.', '/uploads/resumes/resume_48.pdf'),
(49, 'Experienced private tutor (Math & Physics)', 'Experienced private tutor (Math & Physics). Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Computer Science, University of Dhaka (2022)', '1 year as a freelance photographer for local events.', '/uploads/resumes/resume_49.pdf'),
(50, 'Certified electrician available for short-term work', 'Certified electrician available for short-term work. Looking for flexible, short-term opportunities in Dhaka and nearby areas.', 'B.Sc. in Civil Engineering, BUET (2023)', '2 years of general labor and moving assistance work.', '/uploads/resumes/resume_50.pdf');

-- ----------------------------------------------------------------------------
-- SECTION 7 — RESUME_SKILLS (M:N junction; 2-4 skills per resume)
-- ----------------------------------------------------------------------------
INSERT INTO Resume_Skills (resume_id, skill_id) VALUES
(1, 10),
(1, 1),
(2, 9),
(2, 7),
(2, 6),
(3, 9),
(3, 11),
(4, 1),
(4, 7),
(4, 8),
(5, 7),
(5, 6),
(6, 8),
(6, 3),
(6, 7),
(6, 11),
(7, 9),
(7, 11),
(7, 5),
(7, 12),
(8, 8),
(8, 7),
(8, 10),
(9, 6),
(9, 4),
(9, 2),
(10, 8),
(10, 4),
(10, 12),
(11, 10),
(11, 11),
(11, 7),
(11, 6),
(12, 8),
(12, 6),
(13, 8),
(13, 4),
(14, 5),
(14, 6),
(14, 12),
(15, 12),
(15, 5),
(15, 9),
(15, 1),
(16, 4),
(16, 2),
(16, 12),
(16, 7),
(17, 9),
(17, 4),
(17, 8),
(18, 12),
(18, 8),
(18, 11),
(18, 1),
(19, 5),
(19, 4),
(20, 12),
(20, 4),
(20, 5),
(21, 10),
(21, 6),
(21, 8),
(21, 9),
(22, 6),
(22, 7),
(22, 9),
(22, 12),
(23, 12),
(23, 8),
(23, 5),
(24, 5),
(24, 4),
(24, 2),
(25, 4),
(25, 6),
(25, 2),
(25, 9);

-- ----------------------------------------------------------------------------
-- SECTION 8 — APPLICATIONS (45 rows; respects UNIQUE(job_id, seeker_id) — R10)
-- ----------------------------------------------------------------------------
INSERT INTO Applications (job_id, seeker_id, resume_id, cover_message, status_id, applied_at) VALUES
(23, 50, 25, 'I believe I''m a strong fit for this role and can start right away.', 1, DATE_SUB(NOW(), INTERVAL 24 DAY)),
(9, 41, 16, 'Happy to discuss rate and availability over a quick call.', 2, DATE_SUB(NOW(), INTERVAL 25 DAY)),
(20, 42, 17, 'I''ve done similar work before and can share references if needed.', 3, DATE_SUB(NOW(), INTERVAL 27 DAY)),
(10, 32, 7, 'I believe I''m a strong fit for this role and can start right away.', 1, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(23, 26, 1, 'I live nearby and can be on-site quickly if selected.', 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(18, 27, 2, 'I''ve done similar work before and can share references if needed.', 2, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(28, 46, 21, 'Available on short notice and flexible with timing.', 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(10, 44, 19, 'Available on short notice and flexible with timing.', 2, DATE_SUB(NOW(), INTERVAL 11 DAY)),
(2, 31, 6, 'I''ve done similar work before and can share references if needed.', 3, DATE_SUB(NOW(), INTERVAL 16 DAY)),
(27, 29, 4, 'I have relevant experience and am available immediately.', 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(21, 44, 19, 'Happy to discuss rate and availability over a quick call.', 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(8, 28, 3, 'I have relevant experience and am available immediately.', 2, DATE_SUB(NOW(), INTERVAL 14 DAY)),
(20, 45, 20, 'I live nearby and can be on-site quickly if selected.', 1, DATE_SUB(NOW(), INTERVAL 17 DAY)),
(15, 38, 13, 'Available on short notice and flexible with timing.', 1, DATE_SUB(NOW(), INTERVAL 19 DAY)),
(10, 39, 14, 'I live nearby and can be on-site quickly if selected.', 2, DATE_SUB(NOW(), INTERVAL 20 DAY)),
(4, 49, 24, 'I believe I''m a strong fit for this role and can start right away.', 2, DATE_SUB(NOW(), INTERVAL 9 DAY)),
(3, 47, 22, 'I believe I''m a strong fit for this role and can start right away.', 1, DATE_SUB(NOW(), INTERVAL 18 DAY)),
(6, 28, 3, 'I have relevant experience and am available immediately.', 1, DATE_SUB(NOW(), INTERVAL 23 DAY)),
(16, 45, 20, 'I''ve done similar work before and can share references if needed.', 1, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(10, 48, 23, 'Happy to discuss rate and availability over a quick call.', 3, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(8, 47, 22, 'I''ve done similar work before and can share references if needed.', 3, DATE_SUB(NOW(), INTERVAL 21 DAY)),
(22, 44, 19, 'I believe I''m a strong fit for this role and can start right away.', 1, DATE_SUB(NOW(), INTERVAL 18 DAY)),
(21, 33, 8, 'I believe I''m a strong fit for this role and can start right away.', 3, DATE_SUB(NOW(), INTERVAL 27 DAY)),
(3, 30, 5, 'I have relevant experience and am available immediately.', 1, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(24, 45, 20, 'I live nearby and can be on-site quickly if selected.', 3, DATE_SUB(NOW(), INTERVAL 15 DAY)),
(15, 29, 4, 'Happy to discuss rate and availability over a quick call.', 1, DATE_SUB(NOW(), INTERVAL 13 DAY)),
(17, 34, 9, 'I live nearby and can be on-site quickly if selected.', 2, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(2, 45, 20, 'Available on short notice and flexible with timing.', 2, DATE_SUB(NOW(), INTERVAL 20 DAY)),
(1, 34, 9, 'I have relevant experience and am available immediately.', 1, DATE_SUB(NOW(), INTERVAL 22 DAY)),
(19, 44, 19, 'I have relevant experience and am available immediately.', 3, DATE_SUB(NOW(), INTERVAL 22 DAY)),
(19, 34, 9, 'I have relevant experience and am available immediately.', 3, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(17, 41, 16, 'Happy to discuss rate and availability over a quick call.', 1, DATE_SUB(NOW(), INTERVAL 9 DAY)),
(19, 31, 6, 'Available on short notice and flexible with timing.', 2, DATE_SUB(NOW(), INTERVAL 16 DAY)),
(16, 28, 3, 'I''ve done similar work before and can share references if needed.', 1, DATE_SUB(NOW(), INTERVAL 11 DAY)),
(4, 47, 22, 'I believe I''m a strong fit for this role and can start right away.', 1, DATE_SUB(NOW(), INTERVAL 23 DAY)),
(10, 41, 16, 'Happy to discuss rate and availability over a quick call.', 3, DATE_SUB(NOW(), INTERVAL 27 DAY)),
(18, 50, 25, 'I have relevant experience and am available immediately.', 2, DATE_SUB(NOW(), INTERVAL 11 DAY)),
(11, 34, 9, 'I have relevant experience and am available immediately.', 3, DATE_SUB(NOW(), INTERVAL 13 DAY)),
(27, 42, 17, 'I have relevant experience and am available immediately.', 2, DATE_SUB(NOW(), INTERVAL 18 DAY)),
(14, 40, 15, 'I have relevant experience and am available immediately.', 1, DATE_SUB(NOW(), INTERVAL 12 DAY)),
(25, 45, 20, 'Available on short notice and flexible with timing.', 2, DATE_SUB(NOW(), INTERVAL 25 DAY)),
(7, 27, 2, 'I''ve done similar work before and can share references if needed.', 2, DATE_SUB(NOW(), INTERVAL 30 DAY)),
(15, 35, 10, 'Happy to discuss rate and availability over a quick call.', 2, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(20, 46, 21, 'I believe I''m a strong fit for this role and can start right away.', 2, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(1, 43, 18, 'I live nearby and can be on-site quickly if selected.', 1, DATE_SUB(NOW(), INTERVAL 8 DAY));

-- ----------------------------------------------------------------------------
-- SECTION 9 — SAVED_JOBS (40 rows; composite PK (seeker_id, job_id))
-- ----------------------------------------------------------------------------
INSERT INTO Saved_Jobs (seeker_id, job_id, saved_at) VALUES
(29, 15, DATE_SUB(NOW(), INTERVAL 8 DAY)),
(46, 27, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(41, 30, DATE_SUB(NOW(), INTERVAL 19 DAY)),
(42, 23, DATE_SUB(NOW(), INTERVAL 18 DAY)),
(39, 27, DATE_SUB(NOW(), INTERVAL 31 DAY)),
(41, 8, DATE_SUB(NOW(), INTERVAL 30 DAY)),
(43, 5, DATE_SUB(NOW(), INTERVAL 25 DAY)),
(32, 30, DATE_SUB(NOW(), INTERVAL 39 DAY)),
(42, 24, DATE_SUB(NOW(), INTERVAL 9 DAY)),
(28, 9, DATE_SUB(NOW(), INTERVAL 27 DAY)),
(36, 30, DATE_SUB(NOW(), INTERVAL 33 DAY)),
(34, 27, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(35, 24, DATE_SUB(NOW(), INTERVAL 20 DAY)),
(44, 19, DATE_SUB(NOW(), INTERVAL 32 DAY)),
(30, 15, DATE_SUB(NOW(), INTERVAL 35 DAY)),
(41, 12, DATE_SUB(NOW(), INTERVAL 22 DAY)),
(43, 25, DATE_SUB(NOW(), INTERVAL 35 DAY)),
(38, 15, DATE_SUB(NOW(), INTERVAL 21 DAY)),
(32, 23, DATE_SUB(NOW(), INTERVAL 16 DAY)),
(44, 13, DATE_SUB(NOW(), INTERVAL 15 DAY)),
(50, 14, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(36, 24, DATE_SUB(NOW(), INTERVAL 31 DAY)),
(48, 30, DATE_SUB(NOW(), INTERVAL 25 DAY)),
(38, 22, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(41, 2, DATE_SUB(NOW(), INTERVAL 9 DAY)),
(42, 19, DATE_SUB(NOW(), INTERVAL 22 DAY)),
(29, 28, DATE_SUB(NOW(), INTERVAL 29 DAY)),
(29, 17, DATE_SUB(NOW(), INTERVAL 30 DAY)),
(26, 24, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(39, 28, DATE_SUB(NOW(), INTERVAL 10 DAY)),
(28, 16, DATE_SUB(NOW(), INTERVAL 17 DAY)),
(36, 20, DATE_SUB(NOW(), INTERVAL 26 DAY)),
(46, 3, DATE_SUB(NOW(), INTERVAL 22 DAY)),
(47, 28, DATE_SUB(NOW(), INTERVAL 35 DAY)),
(38, 11, DATE_SUB(NOW(), INTERVAL 32 DAY)),
(43, 2, DATE_SUB(NOW(), INTERVAL 40 DAY)),
(28, 8, DATE_SUB(NOW(), INTERVAL 19 DAY)),
(33, 24, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(39, 4, DATE_SUB(NOW(), INTERVAL 7 DAY)),
(40, 6, DATE_SUB(NOW(), INTERVAL 20 DAY));

-- ============================================================================
-- END OF 02_seed_data.sql
-- Row counts: Users=52, Employers=25, Seekers=25, Companies=20, Jobs=30,
-- Resumes=25, Resume_Skills=78, Applications=45, Saved_Jobs=40
-- ============================================================================
